### ISSUE TITLE
Changelog Number missing + Title of window is wrong.

### ISSUE THREAD

**Issue by Nieme** [TeaSpeak/TeaClient#11]
On the newist changelog the number is displayed as X.X.X
http://puu.sh/DYMmx/a9dac62199.png
And on the title, the text "TeaClient ChangeLog" is wrong and need to be change into "TeaClient - Changelog"

**Comment by WolverinDEV** [comment]
We could consider the `-`, but everything else has already be fixed :)

**Comment by WolverinDEV** [comment]
Closed
