### ISSUE TITLE
Crash W/Dump 

### ISSUE THREAD

**Issue by MaverickTN** [TeaSpeak/TeaClient#13]
I am running client version 1.3.6-2 Windows x64
I deleted my %AppData%\TeaClient folder and it still crashed.

[crash_dump_main_20190826-165558-1848-23228.zip](https://github.com/TeaSpeak/TeaClient/files/3543657/crash_dump_main_20190826-165558-1848-23228.zip)

**Comment by WolverinDEV** [comment]
Hey,
I'm already working on this problem.
This is related to electron and the source isn't yet known.
It will may change with the new design, or a few versions after. I'll then tackle the problem more intensive.

Best regards
Markus

**Comment by WolverinDEV** [comment]
fixed :)
