### ISSUE TITLE
My TeaSpeak klient crash

### ISSUE THREAD

**Issue by Zaltimo** [TeaSpeak/TeaClient#14]
I have a problem with TS Client every open application auto close with show error and dump file create I dont know why I was try reinstall delete application nothing
[crash_dump_main_20190829-220308-7736-2592.zip](https://github.com/TeaSpeak/TeaClient/files/3556992/crash_dump_main_20190829-220308-7736-2592.zip)

**Comment by WolverinDEV** [comment]
Hey,
I'm already working on this problem.
This is related to electron and the source isn't yet known.
It will may change with the new design, or a few versions after. I'll then tackle the problem more intensive.

Best regards
Markus

**Comment by WolverinDEV** [comment]
fixed :)
