### ISSUE TITLE
Absturz nach Verbinden

### ISSUE THREAD

**Issue by stgmultigaming** [TeaSpeak/TeaClient#20]
Der Windows Client stürtzt bei mir rund 5 Sekunden nach dem verbinden mit einem Server ab.
[Hier mal ein paar Crash Dumps von 2 unterschiedlichen Tagen](https://pve.stgmultigaming.de/crash_dumps.tar)

**Comment by WolverinDEV** [comment]
Hey,
ich werd mir das morgen mal anschauen.
Hast du auch noch ne Version für mich? :D

**Comment by stgmultigaming** [comment]
{"version":"1.4.2-7 [1580765112428]","timestamp":1580765112428}
Laut app_version.json

**Comment by WolverinDEV** [comment]
Update to 1.4.3-2 it should be fixed there :)

**Comment by WolverinDEV** [comment]
Closed, seems to be fixed
