### ISSUE TITLE
TeaClient Bugs and New Features List

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaClient#23]
TeaSpeak Client Bugs:
- [x] Sometimes sound is not captured well (we need to constantly edit the "Sensitivity settings")
- [x] Last private chat conversation can not be deleted (i speak with 10 users, when deleting all the conversations, latest user chat still remains)
- [x] When changing the MusicBot name, the name does not update (we need to click in a random channel, for example, so it shows the new musicbot name)
- [x] Empty space bug in CH tree when changing to another tab
- [x] The "blue light" that turns on when the user talks, is always on (just happening in TS3 client users) 
- [x] Sometimes the sound is not good (some noises / "crack" sounds)  
- [x] Soundpack volume adjustment not working
- [x] USB HeadPhones with sound Problems 
(Everytime anybody speaks, there is a strange sound at the begining and at the end of the voice)
- [ ] Linux client is not being updated for a long time
- [ ] Deleting CH massages not working properly (server issue)
(after deleting the messages, if you disconnect and reconnect the client, some messages are still present)
- [ ] Some TeaMusicbot chat messages can not be deleted (server issue)

----------------------------------------------------------------------------------------------------------

TeaSpeak Client New Features:
- ~~Add Option to specify the maximum musicbots per virtual server~~ (Server feature request)
- ~~Add Possibility to stream users screen / game~~ (Will not come in near time; Maybe TeaSpeak 2.0)
- [x] Add Option to open links with main navigator (chrome, firefox, safari...)
- [x] Add Code signing certificate
- [x] Add Option to duplicate bookmarks
- [x] Add Poke history (so it shows in general chat)
- [x] Add Icon that appears in the task bar (the icon that shows when client is talking or not)
- [x] Add Option to resize / change size of the embed chat videos
- [x] Add Possibility to play watch2gether videos
- [ ] Add beta / stable update options
- [ ] Add option to mute the teamusicbot
- [ ] Add Possibility to play embed video streams (like twitch and other video / stream websites..)
- [ ] Add TeaSpeak server list (client and server side)
- [ ] Add Option that detects the games users are playing
- [ ] Add Better Soundpack voices

----------------------------------------------------------------------------------------------------------

TeaSpeak Client New Releases:
- [ ] Create TeaSpeak Mac OS client 
- [ ] Create TeaSpeak Android client
- [ ] Create TeaSpeak IOS client

I'll keep this list updated ;)

**Comment by WolverinDEV** [comment]
> The "blue light" that turns on when the user talks, is always on (just happening in TS3 client users)

Locally fixed, will be fixed in an update soon

> Last private chat conversation can not be deleted

That's wanted behaviour. The messages are saved even though close it.
So you're able to read the last few messages again. But may an option within the context menu like "clear history" would be helpfull.

> I delete a CH conversation

I guess its the same point as your first point isn't it?

**Comment by cyberlimbo** [comment]
"I guess its the same point as your first point isn't it?"
No, one thing is private chat conversation, another thing is CH conversation..
Anyway, i removed this one cause it is not happening anymore..

**Comment by WolverinDEV** [comment]
> Add Option to open links with main navigator (chrome, firefox, safari...)

Already possible (right click a link)

> Add Possibility to stream users screen / game
Currently not in near time (I'll cross this out.)

This may will be TeaSpea 2.0 somewhen

>  Add Possibility to create a TeaQueryBot (like jts3servermod) with "Create TeaQueryBot" option

Not sure what this means? TeaSpeak has a query interface but I'll not develop any bots.

> Add Possibility to play video streams (like twitch, youtube videos and other video / stream websites..)

Youtube links are already embetted, not sure what you mean.

**Comment by DWKevinos** [comment]
> > Add Possibility to play video streams (like twitch, youtube videos and other video / stream websites..)
> 
> Youtube links are already embetted, not sure what you mean.

It would be nice to do this is to do like teamusic, that we can create a bot, but which allows us to display an ifram code html/php E.G https://dev.twitch.tv/docs/embed/everything

**Comment by WolverinDEV** [comment]
That link is only for twitch.
I don't think that playing videos via the bot will be a thing quite soon, especially syncing is quite hard.
But implementing something like watch2gether for videos which have been posted within the channel seems possible.

**Comment by cyberlimbo** [comment]
"The "blue light" that turns on when the user talks, is always on (just happening in TS3 client users) (Fixed in 1.4.6-beta2)"
It is better but it is not completely fixed.
(when it is really fixed i always update in the "TeaClient Bugs and New Features List")

"Add Option to open links with main navigator (chrome, firefox, safari...)
Already possible (right click a link)"
Right click and it says "Open URL" (opens with tea navigator) and "Copy URL to clipboard".
Maybe it is better to add a "Open URL with main navigator" option or something.
"You're in TeaWeb website preview mode. Click here to open the website in the browser"
This message sometimes is showing and sometimes not..

"Add Possibility to play video streams (like twitch, youtube videos and other video / stream websites..)
Youtube links are already embetted, not sure what you mean."
I mean watching twitch / youtube streams or videos using the bot, it is really a good feature if possible.
Anyway, if you can include twitch links in embedded, it will be enought for now.

"But implementing something like watch2gether for videos which have been posted within the channel seems possible."
Thats good to know..  users are always asking about that..

**Comment by DWKevinos** [comment]
Add option for server list?

**Comment by cyberlimbo** [comment]
> Add option for server list?

yeah, own teaspeak server list ;)
(that needs to be implemented in server side as well)
Example: 
teaspeak_allow_weblist: 1

**Comment by WolverinDEV** [comment]
Okey could you may split up your collection into single issues to be discussed about?
Thanks ;)

**Comment by dhiaabdelli** [comment]
My idea is you need to have permission called "team_blablabla" to access the channel "blablabla" if its possible ofc :p

**Comment by cyberlimbo** [comment]
Updated.

**Comment by cyberlimbo** [comment]
List updated!

**Comment by WolverinDEV** [comment]
Updated your list a bit.
Please split up every entry into a new single issue!

I'll close this thread soonly because you can't really keep track of any status updates of each single entry.
Also the discussion feature misses.

**Comment by WolverinDEV** [comment]
> Add Icon that appears in the task bar (the icon that shows when client is talking or not)

Implemented in 1.4.11

**Comment by cyberlimbo** [comment]
> Updated your list a bit.
> Please split up every entry into a new single issue!
> 
> I'll close this thread soonly because you can't really keep track of any status updates of each single entry.
> Also the discussion feature misses.

Sorry..  still in holidays time and doing some changes in my home..  I'll do it this month!
Anyway, keep your good work..  The "bugs and new features list" is almost concluded ;)

**Comment by cyberlimbo** [comment]
Updated.
" Please split up every entry into a new single issue! "
Done ;)

**Comment by WolverinDEV** [comment]
Closed due to manageability
