### ISSUE TITLE
Felher mit einem TS3 Server

### ISSUE THREAD

**Issue by Pdzly** [TeaSpeak/TeaClient#28]
Hi,

Ich habe ein Problem mit dem Client wenn ich auf `meints3.com` joinen will crasht der client.

Crash Dump ist angehängt (oder hier: [crash_dump_renderer_20200523-165950-13792-4468.zip](https://github.com/TeaSpeak/TeaClient/files/4671992/crash_dump_renderer_20200523-165950-13792-4468.zip) )

**Comment by WolverinDEV** [comment]
Danke für den Report.
Ich wer mir diesen anschauen.

Update: Der Client crashed auch bei mir.
Dieser Fehler wird behoben ;)

**Comment by WolverinDEV** [comment]
Also eine kurze Analyse ergab, dass es an TSDNS liegt.
Explizit, wenn ein TSDNS Eintrag vorhanden ist, aber der Server "down" ist.
Wird im nächsten update gefixt sein.

Wie wichtig ist dir der Crash? BZW kannst du den TSDNS Eintrag rausnehmen, dann sollte erst mal alles gehen? (Ich würde ungern für nur einen crash alle Clients ein Update fahren lassen, da ich in 3 bis 4 Wochen sowieso ein größeres geplant habe).

**Comment by Pdzly** [comment]
Ne das ist ein Ts3 wo ich mit freunden treff so.wichtig ist das auch nicht nur halt das es halt dieser bug irgendwann gefixt wird.Am 29.05.20, 10:56 schrieb WolverinDEV <notifications@github.com>:

   
  Also eine kurze Analyse ergab, dass es an TSDNS liegt. Explizit, wenn ein TSDNS Eintrag vorhanden ist, aber der Server "down" ist. Wird im nächsten update gefixt sein. 
  Wie wichtig ist dir der Crash? BZW kannst du den TSDNS Eintrag rausnehmen, dann sollte erst mal alles gehen? (Ich würde ungern für nur einen crash alle Clients ein Update fahren lassen, da ich in 3 bis 4 Wochen sowieso ein größeres geplant habe).

**Comment by WolverinDEV** [comment]
Fixed in 1.4.8
