### ISSUE TITLE
Application doesn't start

### ISSUE THREAD

**Issue by Pega16** [TeaSpeak/TeaClient#29]
simple Start after installation fails...

CrashDump attached... just RENAME it (remove .zip) to open (because GIThub doesn't support .dmp files...
[crash_dump_renderer_20200602-085626-23972-25968.dmp.zip](https://github.com/TeaSpeak/TeaClient/files/4715384/crash_dump_renderer_20200602-085626-23972-25968.dmp.zip)

**Comment by WolverinDEV** [comment]
Hey,
thanks for the report.
I'll have a look when I'm back home ;)


Which OS do you use? As well which client version?

**Comment by xLamday** [comment]
Pega16, try to restart the program much times, it worked to me.

**Comment by xLamday** [comment]
@WolverinDEV I can translate TeaSpeak in italian if you want. If you want to make me translate the program, contact me via email, xlamdaygamer2@gmail.com

**Comment by WolverinDEV** [comment]
I think this is actually related to this topic: https://github.com/TeaSpeak/TeaClient/issues/36
We'll see the results of the no crash handler possibility and if it works flawless than.
