### ISSUE TITLE
Client crashes if nvidia image sharpening is enabled

### ISSUE THREAD

**Issue by Pingger** [TeaSpeak/TeaClient#31]
Hi,

TeaSpeak crashes instantly after splashscreen. (Downloads Theme and stuff, but crashes afterwards)

Cause: Image Sharpening in NVIDIA Control Panel is enabled

Version: 1.4.8 (according to the installer)
OS: Windows 10 x64

[crash_dump_renderer_20200613-201243-14656-6668.zip](https://github.com/TeaSpeak/TeaClient/files/4775160/crash_dump_renderer_20200613-201243-14656-6668.zip)

Greetings

**Comment by WolverinDEV** [comment]
When disabling this feature doesn't it crash anymore?

**Comment by Pingger** [comment]
correct.

**Comment by WolverinDEV** [comment]
Okey, I've an idea but I'll lookup the crash dumps later ;)

**Comment by WolverinDEV** [comment]
Thanks for good trouble shooting.

**Comment by WolverinDEV** [comment]
Hmm what the hell is this image sharpening?
![](https://img.did.science/Screenshot_13-46-40.png)

BTW Sadly I can't really reproduce that....

**Comment by Pingger** [comment]
In the nVidia control panel ... And for some reason the default setting since over a few releases. But as can be seen in the screenshot, it is no longer the default setting.
![image](https://user-images.githubusercontent.com/4761298/90887750-34a47400-e3b5-11ea-8387-58c9c75adf05.png)

**Comment by WolverinDEV** [comment]
Hmm even thou I used your settings I can't reproduce that error, but I've an idea.
Wait for the next client release. I've added a flag to disable the crash handler.

My guess is that some kind of render process crashes (from electron itself), but it isn't critical for the app itself... 
But since my crash handler shut downs the client, the client closes.

**Comment by WolverinDEV** [comment]
Well can you may tryout to start the client with this switch: `--no-crash-renderer`?
