### ISSUE TITLE
Debian Linux Client crash right after it opens main window.

### ISSUE THREAD

**Issue by pvlopez00** [TeaSpeak/TeaClient#32]
[crash_dump_renderer_4fe540de-b788-46be-816f69a2-123bd3d6.zip](https://github.com/TeaSpeak/TeaClient/files/4816939/crash_dump_renderer_4fe540de-b788-46be-816f69a2-123bd3d6.zip)

**Comment by WolverinDEV** [comment]
Windows or linux ;)

**Comment by pvlopez00** [comment]
Linux, it happens to the Linux Client I haven't tested on Windows yet.

**Comment by WolverinDEV** [comment]
Fixed, Linux client has been updated
