### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by lexesv** [TeaSpeak/TeaClient#34]
[crash_dumps.zip](https://github.com/TeaSpeak/TeaClient/files/4941418/crash_dumps.zip)

**Comment by WolverinDEV** [comment]
Windows/linux?

**Comment by lexesv** [comment]
Computer
Processor | Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
Memory | 32781MB (13230MB used)
Machine Type | Desktop
Operating System | Debian GNU/Linux 10 (buster)
Display
Resolution | 2560x1440 pixels
OpenGL Renderer | GeForce GTX 950/PCIe/SSE2
X11 Vendor | The X.Org Foundation
Audio Devices
Audio Adapter | HDA-Intel - HDA Intel PCH
Audio Adapter | HDA-Intel - HDA NVidia
