### ISSUE TITLE
crash on first launch (after install)

### ISSUE THREAD

**Issue by MyUncleSam** [TeaSpeak/TeaClient#36]
Hi there,

I installed teaspeak for the first time and directly after the installation finished it crashed. I attached the crash dump.
[crash_dump_renderer_20200811-184214-20980-21412.zip](https://github.com/TeaSpeak/TeaClient/files/5058235/crash_dump_renderer_20200811-184214-20980-21412.zip)

**Comment by WolverinDEV** [comment]
Did this crash only occurred once or every time?
PS: I think it can be related to this one: https://github.com/TeaSpeak/TeaClient/issues/31#issuecomment-678681986
