### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nieme** [TeaSpeak/TeaClient#4]
https://www.chromatic-solutions.de/crash_dump_renderer_20190709-171258-3140-10732.dmp

[crash_dump_renderer_20190709-171258-3140-10732.log](https://github.com/TeaSpeak/TeaClient/files/3374120/crash_dump_renderer_20190709-171258-3140-10732.log)

**Comment by WolverinDEV** [comment]
fixed in beta 1 :)
Thanks for your passions and your report.
