### ISSUE TITLE
Create Android, iOS and Mac OS clients

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaClient#45]
Create TeaSpeak Android client. 
Create TeaSpeak IOS client.
Create TeaSpeak Mac OS client.

*This is an old sugestion, i'm just splitting up every entry into a new single issue so users can discuss about it.

**Comment by WolverinDEV** [comment]
before issue https://github.com/TeaSpeak/TeaWeb/issues/143 isn't resolved it makes no sense to have one here
