### ISSUE TITLE
General chat window bug

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaClient#48]
The general chat completely disappears after some time.

**Comment by cyberlimbo** [comment]
**Please, do not forget about this bug.
It is annoying not having the general chat present after some time xD

**Comment by WolverinDEV** [comment]
Well actually it's the first time seeing this.
If you're not having a chat any more, it means that something crashed within the renderer.

I know that I've fixed a while a go one crash, which may lead to that, but not sure if the client already has that UI update.
To resolve your issue I need the client log, just open the client via the terminal, or directly use the build in dev tools (start the client with `-t`)

**Comment by cyberlimbo** [comment]
ok.
Sent by forum pm, home it helps ;)

**Comment by cyberlimbo** [comment]
This bug seems to be solved.

//closed
