### ISSUE TITLE
Studio Microfone Audio Problem

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaClient#49]
I'm using a studio microfone and the sound with teaspeak is only working in left side.
*I tested with ts3client just to compare and there is no problem, the sound it is working in both sides.

**Comment by WolverinDEV** [comment]
Are you using a stereo or mono recording?

**Comment by cyberlimbo** [comment]
No matter if i use mono or stereo in windows sound settings, it is giving the same result.
With normal headphones that include microfone, there are no problems, with studio microfone,
sound is just working in left side.
I tested all the microfone options from the teaspeak client, but still the same problem.
*tested with ts3 client and no problems.

**Comment by cyberlimbo** [comment]
Problem solved ;)
If somebody is with the same problem, check this video to solve it ;)
https://www.youtube.com/watch?v=_qG3bWQ7Aqg
