### ISSUE TITLE
Invalid number of channel, USB Microphone

### ISSUE THREAD

**Issue by arosso96** [TeaSpeak/TeaClient#50]
System Information
Operating System : Windows 10 19041.508

Issue
Reason for reporting this issue: Problem with the usage of USB Microphones

Detailed Description: Unable to use the USB Microphone directly on TeaSpeak because it cannot read the correct number of channels (it reads -9998), probably this could be solved by forcing the number of channel to 1 or 2 (seems similar to: Uberi/speech_recognition#139 , https://stackoverflow.com/questions/31073667/getting-ioerror-errno-invalid-number-of-channels-9998-when-using-mic-with-py , https://www.raspberrypi.org/forums/viewtopic.php?t=71062)

![issue](https://user-images.githubusercontent.com/38297202/99148629-18993180-2689-11eb-80b8-9ba7c2eb162d.png)

**Comment by WolverinDEV** [comment]
Yes TeaSpeak usually enforced one microphone channel.
This is kinda a bug which should be solved.

PS: Thanks for your excellent research.

**Comment by WolverinDEV** [comment]
Should be fixed ;)
Use 1.5.0-nightly3 ;)
