### ISSUE TITLE
Add possibility to connect with nicknames

### ISSUE THREAD

**Issue by cyberlimbo** [TeaSpeak/TeaClient#51]
-Add possibility to teaspeak client so we can connect the teaspeak servers using nicknames.

**Comment by WolverinDEV** [comment]
TeaSpeak don't offer any server nicknames.

**Comment by cyberlimbo** [comment]
I know xD
But maybe you can implement it?

**Comment by WolverinDEV** [comment]
Nah I'm tbh not really a friend on that feature...
What's the benefit of it?

**Comment by cyberlimbo** [comment]
not using dns's for example..
instead of connecting to "ts.teaspeak.de" we can simply connect to "teaspeak" ;)
That's interesting in a lot users point of view.. (but not really urgent/important)
