### ISSUE TITLE
An issue with my payment‏‏

### ISSUE THREAD

**Issue by C4SP3R1337** [TeaSpeak/TeaClient#68]
I have made my payment from my paypal within a wrong email address.

I need to change the email address to adel62734@gmail.com instead of adel62734@gamil.com

and send me the new panel information.

Here's a proof from the payment.

[https://prnt.sc/1xra4q5](url)

**Comment by WolverinDEV** [comment]
Hey,
you can change the e-mail address of your account and then resend your license code.

**Comment by C4SP3R1337** [comment]
Please Send me The panal agian 

<14:31:31> Server has been shut down: server deleted
why this msg ?

**Comment by C4SP3R1337** [comment]
i cant open the VIP WEB PANEL please reset this

‫في الأحد، 31 أكتوبر 2021 في 11:12 ص تمت كتابة ما يلي بواسطة ‪WolverinDEV‬‏
***@***.***‬‏>:‬

**Comment by WolverinDEV** [comment]
Hello,
we don't provide any server not a VIP web pannel.
