### ISSUE TITLE
Installing on linux from tar.gz

### ISSUE THREAD

**Issue by Slime90** [TeaSpeak/TeaClient#71]
How does one go about installing/executing the client on any non debian based linux using the provided tar.gz? What are the dependencies for doing so?There is no README or instructions anywhere I can find.

**Comment by WolverinDEV** [comment]
Hey,
TeaSpeak should run on every libc based system.
There are no other dependencies.

**Comment by Slime90** [comment]
Thank you, my issue was with interpreter lib pathing, closing.
