### ISSUE TITLE
Bind Mouse4 or Mouse5 for PTT

### ISSUE THREAD

**Issue by Mifilca** [TeaSpeak/TeaClient#8]
like the title say im not able to bind mouse4 and mous5 this is the only think that is separating me from using TeaSpeakClient i really like the client but im too used to this bind.

**Comment by WolverinDEV** [comment]
I haven't tested keys like mouse4/5 because I just use a regular mouse, but in general this should work with the next client update and the new style.

Keys like CTRL or SHIFT only are from now on also supported.

**Comment by Mifilca** [comment]
After update 1.4.0 im still not able to select this key.
None of the mouse keys work mouse 1/2/3/4/5

**Comment by WolverinDEV** [comment]
Implemented all mouse keys:
- `MOUSE1` (right button)
- `MOUSE2` (left button)
- `MOUSE1` (middle button)
- `MOUSEX1` (First extra button)
- `MOUSEX2` (Second extra button)

(1.4.2)
